### ISSUE TITLE
Compilation Error When Installing the bsynth Package in R

### ISSUE THREAD

**Issue by thiagosfelipe** [google/bsynth#6]
Hello,

I am encountering a problem while trying to install the bsynth package using R and would appreciate any help in resolving the following compilation errors:

stanExports_factor_functions.h:254: error: 'in__' was not declared in this scope
stanExports_factor_functions.h:258: error: 'prog_reader__' was not declared in this scope
stanExports_factor_functions.h:292: error: 'in__' was not declared in this scope
stanExports_factor_functions.h:306: error: 'prog_reader__' was not declared in this scope
make: *** [C:/PROGRA~1/R/R-4.4.1/etc/x64/Makeconf:294: stanExports_factor_functions.o] Error 1
ERROR: compilation failed for package 'bsynth'
* removing 'C:/..../AppData/Local/R/win-library/4.4/bsynth'

These errors suggest there are variables not declared within the expected scope, and I am unsure if this is an issue with my development environment or a problem with how the bsynth package integrates with R.

Questions:
Is there any specific configuration or dependency that I might have missed for successfully installing bsynth in R?
Is the bsynth package compatible with the latest version of R, or would it be advisable to try in a different environment?
I appreciate any help or guidance you can provide to resolve this issue.

Best regards,

**Comment by ignacio82** [comment]
can you install it from [Cran](https://cran.r-project.org/web/packages/bsynth/index.html)?

**Comment by thiagosfelipe** [comment]
I was able to install the package using the CRAN from R. Thank you for the suggestion!
